import { PlanId, SubjectId, UserId } from './ids';

export class Exercise {
  planId: PlanId;
  planName: string; //union type would be mre suitable
  subjectId: SubjectId;
  startDate: Date;
  teacherId: UserId;
  autoGenerated: boolean;
  planJson: Text;
}
