import { Column, Entity, PrimaryColumn } from 'typeorm';

@Entity({ name: 'plans' })
export class PlanEntity {
  @PrimaryColumn({ name: 'plan_id', type: 'text' })
  planId: string;

  @Column({ name: 'plan_name', type: 'text' })
  planName: string;

  @Column({ name: 'subject_id', type: 'text' })
  subjectId: string;

  @Column({ name: 'start_date', type: 'datetime' })
  startDate: Date;

  @Column({ name: 'total_weeks', type: 'integer' })
  totalWeeks: number;

  @Column({ name: 'teacher_id', type: 'text' })
  teacherId: string;

  @Column({ name: 'sessions_json', type: 'text' })
  sessionsJson: string;

  @Column({ name: 'auto_generated', type: 'boolean' })
  autoGenerated: boolean;

  @Column({ name: 'plan_json', type: 'text' })
  planJson: string;
}
