import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Plan } from 'src/domain/plan';
import { PlanItem } from 'src/domain/plan-item';
import { Session } from 'src/domain/session';
import { PlanRepository } from 'src/repositories/plan.repository';
import { PlanEntity } from './entities/plan.entity';

@Injectable()
export class SqlitePlansRepo implements PlanRepository {
  constructor(
    @InjectRepository(PlanEntity)
    private readonly repository: Repository<PlanEntity>,
  ) {}

  async create(plan: Plan): Promise<Plan> {
    const entity = this.repository.create(this.toEntity(plan));
    const saved = await this.repository.save(entity);
    return this.toDomain(saved);
  }

  async findById(id: string): Promise<Plan | null> {
    const entity = await this.repository.findOneBy({ planId: String(id) });
    return entity ? this.toDomain(entity) : null;
  }

  async findAll(): Promise<Plan[]> {
    const entities = await this.repository.find({
      order: {
        startDate: 'DESC',
      },
    });
    return entities.map((entity) => this.toDomain(entity));
  }

  async update(id: string, patch: Partial<Plan>): Promise<Plan | null> {
    const existing = await this.repository.findOneBy({ planId: String(id) });
    if (!existing) return null;

    const merged = this.repository.merge(
      existing,
      this.toEntityPatch(patch) as Partial<PlanEntity>,
    );
    const saved = await this.repository.save(merged);
    return this.toDomain(saved);
  }

  async delete(id: string): Promise<boolean> {
    const existing = await this.findById(id);
    if (!existing) return false;
    await this.repository.delete({ planId: String(id) });
    return true;
  }

  private toEntity(plan: Plan): PlanEntity {
    return {
      planId: String(plan.planId),
      planName: String(plan.planName),
      subjectId: String(plan.subjectId),
      startDate: new Date(plan.startDate),
      totalWeeks: Number(plan.totalWeeks),
      teacherId: String(plan.teacherId),
      sessionsJson: JSON.stringify(plan.sessions ?? []),
      autoGenerated: Boolean(plan.autoGenerated),
      planJson: String(plan.planJson),
    };
  }

  private toEntityPatch(patch: Partial<Plan>): Partial<PlanEntity> {
    return {
      ...patch,
      planName:
        patch.planName === undefined ? patch.planName : String(patch.planName),
      subjectId:
        patch.subjectId === undefined || patch.subjectId === null
          ? patch.subjectId
          : String(patch.subjectId),
      startDate:
        patch.startDate === undefined || patch.startDate === null
          ? patch.startDate
          : new Date(patch.startDate),
      totalWeeks:
        patch.totalWeeks === undefined || patch.totalWeeks === null
          ? patch.totalWeeks
          : Number(patch.totalWeeks),
      teacherId:
        patch.teacherId === undefined || patch.teacherId === null
          ? patch.teacherId
          : String(patch.teacherId),
      sessionsJson:
        patch.sessions === undefined
          ? undefined
          : JSON.stringify(patch.sessions),
      autoGenerated:
        patch.autoGenerated === undefined
          ? patch.autoGenerated
          : Boolean(patch.autoGenerated),
      planJson:
        patch.planJson === undefined ? patch.planJson : String(patch.planJson),
    };
  }

  private toDomain(entity: PlanEntity): Plan {
    return {
      planId: String(entity.planId),
      planName: entity.planName,
      subjectId: String(entity.subjectId),
      startDate: new Date(entity.startDate),
      totalWeeks: Number(entity.totalWeeks),
      teacherId: String(entity.teacherId),
      sessions: this.parseSessions(entity.sessionsJson),
      autoGenerated: Boolean(entity.autoGenerated),
      planJson: entity.planJson,
    };
  }

  private parseSessions(sessionsJson: string): Session[] {
    const parsed = JSON.parse(sessionsJson) as Session[];
    return Array.isArray(parsed)
      ? parsed.map((session) => ({
          ...session,
          teacherId: String(session.teacherId),
          subjectId: String(session.subjectId),
          sessionDate: new Date(session.sessionDate),
          items: Array.isArray(session.items)
            ? session.items.map((item) => this.normalizePlanItem(item))
            : [],
        }))
      : [];
  }

  private normalizePlanItem(item: PlanItem): PlanItem {
    return {
      ...item,
      planItemId: String(item.planItemId),
      planId: String(item.planId),
      sessionId: String(item.sessionId),
      curriculumItemId: String(item.curriculumItemId),
      subjectId: String(item.subjectId),
      estimatedTime: Number(item.estimatedTime),
      unitNo: Number(item.unitNo),
      lessonNo: Number(item.lessonNo),
      orderInLesson: Number(item.orderInLesson),
      originalEstimatedTime:
        item.originalEstimatedTime === undefined ||
        item.originalEstimatedTime === null
          ? item.originalEstimatedTime
          : Number(item.originalEstimatedTime),
      minEstimatedTime:
        item.minEstimatedTime === undefined || item.minEstimatedTime === null
          ? item.minEstimatedTime
          : Number(item.minEstimatedTime),
      originalSessionOrder:
        item.originalSessionOrder === undefined ||
        item.originalSessionOrder === null
          ? item.originalSessionOrder
          : Number(item.originalSessionOrder),
      carriedForwardCount:
        item.carriedForwardCount === undefined ||
        item.carriedForwardCount === null
          ? item.carriedForwardCount
          : Number(item.carriedForwardCount),
    };
  }
}
