import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { CurriculumItem } from 'src/domain/curriculum-item';
import { SubjectId, UserId } from 'src/domain/ids';
import { Plan } from 'src/domain/plan';
import { Session } from 'src/domain/session';
import { SubjectOffering } from 'src/domain/subjectOffering';
import { InMemoryCurriculumItemsRepo } from 'src/infrastructure/in-memory/in-memory-curriculum-item.repo';
import { InMemoryPlansRepo } from 'src/infrastructure/in-memory/in-memory-plan.repo';
import { InMemorySubjectOfferingsRepo } from 'src/infrastructure/in-memory/in-memory-subjectOffering.repo';
import type { WeekDay, WeeklySlotDTO } from './DTO/save-weekly-slots.dto';
import { PlanInputService } from './plan-input.service';
import { Priority } from 'src/statistics/statistics.service';
import { StatisticsService } from 'src/statistics/statistics.service';

const priorityToPoints: Record<Priority, number> = {
  [Priority.HIGH]: 10,
  [Priority.MID]: 6,
  [Priority.LOW]: 3,
};

export const semesterTotalWeeks: Record<number, number> = {
  1: 16,
  2: 12,
};

const DEFAULT_SESSION_DURATION_MINUTES = 40;
const REVIEW_BUFFER_INTERVAL = 4;
const REVIEW_BUFFER_MINUTES = 10;
const DAY_ORDER: WeekDay[] = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
];

@Injectable()
export class PlansService {
  constructor(
    private readonly statService: StatisticsService,
    private readonly curriculumItemsRepo: InMemoryCurriculumItemsRepo,
    private readonly subjectOfferingsRepo: InMemorySubjectOfferingsRepo,
    private readonly plansRepo: InMemoryPlansRepo,
    private readonly planInputService: PlanInputService,
  ) {}

  async generatePlan(
    teacherId: UserId,
    subjectId: SubjectId,
    semester: 1 | 2,
  ): Promise<Plan> {
    const savedWeeklySlots = this.planInputService.getWeeklySlots(
      teacherId,
      subjectId,
    );

    if (!savedWeeklySlots || savedWeeklySlots.slots.length === 0) {
      throw new BadRequestException(
        'No weekly slots found for this teacher and subject.',
      );
    }

    const subjectOffering = await this.findSubjectOffering(
      teacherId,
      subjectId,
    );
    const requiredItems = await this.curriculumItemsRepo.getRequiredItme({
      grade: subjectOffering.gradeId,
      subject: subjectId,
      semester,
    });

    const orderedItems = this.sortCurriculumItems(requiredItems);
    const timedItems = await Promise.all(
      orderedItems.map((item) => this.calculateEstimatedTime(item)),
    );

    const sessions = this.buildSessionsFromSlots(
      teacherId,
      subjectId,
      this.sortWeeklySlots(savedWeeklySlots.slots),
      timedItems,
      semesterTotalWeeks[semester],
    );

    const planStartDate = sessions[0]?.sessionDate ?? new Date();
    const plan: Plan = {
      planId: `plan_${teacherId}_${subjectId}_${semester}_${Date.now()}`,
      planName: `Auto Plan ${subjectId} S${semester}`,
      subjectId,
      startDate: planStartDate,
      totalWeeks: semesterTotalWeeks[semester],
      teacherId,
      sessions,
      autoGenerated: true,
      planJson: JSON.stringify(
        sessions.map((session) => ({
          sessionId: session.sessionId,
          day: session.day,
          slotNumber: session.slotNumber,
          sessionDate: session.sessionDate.toISOString(),
          reviewBufferMinutes: session.reviewBufferMinutes,
          itemIds: session.items.map((item) => item.curriculumItemId),
        })),
      ),
    };

    await this.plansRepo.create(plan);
    return plan;
  }

  //helper method for sortng the items:

  private sortCurriculumItems(
    curriculumItems: CurriculumItem[],
  ): CurriculumItem[] {
    return [...curriculumItems].sort((a, b) => {
      if (a.unitNo !== b.unitNo) {
        return a.unitNo - b.unitNo;
      }

      if (a.lessonNo !== b.lessonNo) {
        return a.lessonNo - b.lessonNo;
      }

      return a.orderInLesson - b.orderInLesson;
    });
  }

  private async calculateSkillWeight(
    curriculumItem: CurriculumItem,
  ): Promise<number> {
    const priorityRows = await this.statService.sortWeakestSkills();

    const matchedSkill = priorityRows.find((row) =>
      curriculumItem.skillsSupported.includes(row.skillId),
    );

    const priorityPoints = matchedSkill
      ? priorityToPoints[matchedSkill.priority]
      : 0;

    const difficultyToPoints: Record<number, number> = {
      1: 3,
      2: 6,
      3: 10,
    };

    const difficultyPoints =
      difficultyToPoints[curriculumItem.difficulity] ?? 0;

    return priorityPoints + difficultyPoints;
  }

  private weightToMinutes(weight: number): number {
    if (weight >= 18) return 15;
    if (weight >= 14) return 12;
    if (weight >= 10) return 9;
    return 6;
  }

  private async calculateEstimatedTime(
    curriculumItem: CurriculumItem,
  ): Promise<CurriculumItem> {
    const weight = await this.calculateSkillWeight(curriculumItem);
    const minutes = this.weightToMinutes(weight);

    return {
      ...curriculumItem,
      estimatedTime: minutes,
    };
  }

  private async findSubjectOffering(
    teacherId: UserId,
    subjectId: SubjectId,
  ): Promise<SubjectOffering> {
    const offerings = await this.subjectOfferingsRepo.findAll();
    const subjectOffering = offerings.find(
      (offering) =>
        String(offering.teacherId) === String(teacherId) &&
        String(offering.subjectId) === String(subjectId),
    );

    if (!subjectOffering) {
      throw new NotFoundException(
        'No subject offering found for this teacher and subject.',
      );
    }

    return subjectOffering;
  }

  private sortWeeklySlots(slots: WeeklySlotDTO[]): WeeklySlotDTO[] {
    return [...slots].sort((a, b) => {
      const dayDiff = DAY_ORDER.indexOf(a.day) - DAY_ORDER.indexOf(b.day);
      if (dayDiff !== 0) {
        return dayDiff;
      }

      return a.slotNumber - b.slotNumber;
    });
  }

  private buildSessionsFromSlots(
    teacherId: UserId,
    subjectId: SubjectId,
    weeklySlots: WeeklySlotDTO[],
    timedItems: CurriculumItem[],
    totalWeeks: number,
  ): Session[] {
    if (weeklySlots.length === 0 || timedItems.length === 0) {
      return [];
    }

    const sessions: Session[] = [];
    let itemIndex = 0;

    for (let weekIndex = 0; weekIndex < totalWeeks; weekIndex++) {
      const weekNo = weekIndex + 1;
      for (const slot of weeklySlots) {
        if (itemIndex >= timedItems.length) {
          return sessions;
        }

        const sessionNumber = sessions.length + 1;
        const reviewBufferMinutes =
          sessionNumber % REVIEW_BUFFER_INTERVAL === 0
            ? REVIEW_BUFFER_MINUTES
            : 0;
        const availableMinutes =
          DEFAULT_SESSION_DURATION_MINUTES - reviewBufferMinutes;
        const itemsForSession: CurriculumItem[] = [];
        let usedDuration = 0;

        while (itemIndex < timedItems.length) {
          const currentItem = timedItems[itemIndex];
          const itemMinutes = Number(currentItem.estimatedTime ?? 0);

          if (
            itemsForSession.length > 0 &&
            usedDuration + itemMinutes > availableMinutes
          ) {
            break;
          }

          if (itemsForSession.length === 0 && itemMinutes > availableMinutes) {
            itemsForSession.push(currentItem);
            usedDuration += itemMinutes;
            itemIndex++;
            break;
          }

          itemsForSession.push(currentItem);
          usedDuration += itemMinutes;
          itemIndex++;
        }

        sessions.push({
          sessionId: `session_${teacherId}_${subjectId}_${weekIndex + 1}_${slot.day}_${slot.slotNumber}`,
          teacherId: String(teacherId),
          subjectId: String(subjectId),
          day: slot.day,
          items: itemsForSession,
          maxDuration: DEFAULT_SESSION_DURATION_MINUTES,
          usedDuration,
          reviewBufferMinutes,
          slotNumber: slot.slotNumber,
          sessionDate: this.buildSessionDate(slot.day, weekIndex),
        });
      }
    }

    return sessions;
  }

  private buildSessionDate(day: WeekDay, weekIndex: number): Date {
    const now = new Date();
    const startOfWeek = new Date(now);
    startOfWeek.setHours(0, 0, 0, 0);
    startOfWeek.setDate(now.getDate() - now.getDay());

    const dayOffset = DAY_ORDER.indexOf(day);
    const sessionDate = new Date(startOfWeek);
    sessionDate.setDate(startOfWeek.getDate() + weekIndex * 7 + dayOffset);
    return sessionDate;
  }
}
