import {
  BadRequestException,
  ForbiddenException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { CurriculumItem } from 'src/domain/curriculum-item';
import { SubjectId, UserId } from 'src/domain/ids';
import { Plan } from 'src/domain/plan';
import { Session } from 'src/domain/session';
import { SubjectOffering } from 'src/domain/subjectOffering';
import { PlanLog, PlanLogActionType } from 'src/domain/planLog';
import { InMemoryCurriculumItemsRepo } from 'src/infrastructure/in-memory/in-memory-curriculum-item.repo';
import { InMemoryPlansRepo } from 'src/infrastructure/in-memory/in-memory-plan.repo';
import { InMemoryPlanLogsRepo } from 'src/infrastructure/in-memory/in-memory-planLog.repo';
import { InMemorySubjectOfferingsRepo } from 'src/infrastructure/in-memory/in-memory-subjectOffering.repo';
import type { WeekDay, WeeklySlotDTO } from './DTO/save-weekly-slots.dto';
import { PlanInputService } from './plan-input.service';
import { TeacherTodoItem } from './types/teacher-todo-item';
import { Priority } from 'src/statistics/statistics.service';
import { StatisticsService } from 'src/statistics/statistics.service';
import { PlanItem, PlanItemStatus } from 'src/domain/plan-item';
import { randomUUID } from 'crypto';
import { InMemoryPlanItemsRepo } from 'src/infrastructure/in-memory/in-memory-plan-item.repo';
import { InMemorySessionsRepo } from 'src/infrastructure/in-memory/in-memory-session.repo';

const priorityToPoints: Record<Priority, number> = {
  [Priority.HIGH]: 10,
  [Priority.MID]: 6,
  [Priority.LOW]: 3,
};

export const semesterTotalWeeks: Record<number, number> = {
  1: 16,
  2: 12,
};

export type UpdatePlanItemStatusResponse = {
  item: PlanItem;
  session: Session;
  progress: PlanProgressSummary;
};

export type ReplanPaceSummary = {
  behindPace: boolean;
  carriedForwardItemsByDay: Record<string, number>;
};

export type ReplanPlanResponse = {
  plan: Plan;
  pace: ReplanPaceSummary;
  planOverCapacity: boolean;
  unplacedItems: PlanItem[];
};

export type PlanProgressSummary = {
  planId: string;
  totalItems: number;
  completedItems: number;
  remainingItems: number;
  cancelledItems: number;
  progressPercentage: number;
};

const DEFAULT_SESSION_DURATION_MINUTES = 40;
const REVIEW_BUFFER_INTERVAL = 4;
const REVIEW_BUFFER_MINUTES = 10;
const DAY_ORDER: WeekDay[] = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
];

@Injectable()
export class PlansService {
  constructor(
    private readonly statService: StatisticsService,
    private readonly curriculumItemsRepo: InMemoryCurriculumItemsRepo,
    private readonly subjectOfferingsRepo: InMemorySubjectOfferingsRepo,
    private readonly plansRepo: InMemoryPlansRepo,
    private readonly planLogsRepo: InMemoryPlanLogsRepo,
    private readonly planInputService: PlanInputService,
    private readonly planItemRepo: InMemoryPlanItemsRepo,
    private readonly sessionRepo: InMemorySessionsRepo,
  ) {}

  async generatePlan(
    teacherId: UserId,
    subjectId: SubjectId,
    semester: 1 | 2,
  ): Promise<Plan> {
    const planId = `plan_${teacherId}_${subjectId}_${semester}_${Date.now()}`;

    const savedWeeklySlots = this.planInputService.getWeeklySlots(
      teacherId,
      subjectId,
    );

    if (!savedWeeklySlots || savedWeeklySlots.slots.length === 0) {
      throw new BadRequestException(
        'No weekly slots found for this teacher and subject.',
      );
    }

    const subjectOffering = await this.findSubjectOffering(
      teacherId,
      subjectId,
    );
    const requiredItems = await this.curriculumItemsRepo.getRequiredItme({
      grade: subjectOffering.gradeId,
      subject: subjectId,
      semester,
    });

    const orderedItems = this.sortCurriculumItems(requiredItems);
    const timedItems = await Promise.all(
      orderedItems.map((item) => this.calculateEstimatedTime(item)),
    );

    const sessions = this.buildSessionsFromSlots(
      teacherId,
      subjectId,
      this.sortWeeklySlots(savedWeeklySlots.slots),
      timedItems,
      semesterTotalWeeks[semester],
      planId,
    );

    const planStartDate = sessions[0]?.sessionDate ?? new Date();
    const plan: Plan = {
      planId,
      planName: `Auto Plan ${subjectId} S${semester}`,
      subjectId,
      startDate: planStartDate,
      totalWeeks: semesterTotalWeeks[semester],
      teacherId,
      sessions,
      autoGenerated: true,
      planJson: JSON.stringify(
        sessions.map((session) => ({
          sessionId: session.sessionId,
          day: session.day,
          slotNumber: session.slotNumber,
          sessionDate: session.sessionDate.toISOString(),
          reviewBufferMinutes: session.reviewBufferMinutes,
          itemIds: session.items.map((item) => item.curriculumItemId),
        })),
      ),
    };

    await this.plansRepo.create(plan);
    await this.saveGeneratedSessions(sessions);
    await this.logPlanGenerated(plan);
    return plan;
  }

  private async saveGeneratedSessions(sessions: Session[]): Promise<void> {
    for (const session of sessions) {
      await this.sessionRepo.create(session);

      for (const item of session.items) {
        await this.planItemRepo.create(item);
      }
    }
  }

  async updateItemEstimatedTime(
    teacherId: UserId,
    planId: string,
    planItemId: string,
    estimatedMinutes: number,
    sessionId: string,
  ): Promise<Session> {
    const planItem = await this.planItemRepo.findById(planItemId);
    if (!planItem) throw new NotFoundException();
    if (planItem.planId !== planId) {
      throw new BadRequestException('Plan item does not belong to plan.');
    }

    const plan = await this.verifyTeacherOwnsPlan(planId, teacherId);
    const planSession = this.findSessionInPlan(plan, sessionId);
    const item = this.findItemInSession(planSession, planItemId);
    const updatedItem: PlanItem = {
      ...item,
      estimatedTime: estimatedMinutes,
    };

    const session = await this.sessionRepo.findById(sessionId);
    if (!session) throw new NotFoundException();

    this.replaceItemInSession(planSession, updatedItem);
    planSession.usedDuration = this.calculateSessionUsedDuration(planSession);

    this.replaceItemInSession(session, updatedItem);
    session.usedDuration = planSession.usedDuration;

    // TODO: Repack sessions if this update pushes the session over its limit.
    await this.plansRepo.update(plan.planId, { sessions: plan.sessions });
    await this.sessionRepo.update(sessionId, {
      items: session.items,
      usedDuration: session.usedDuration,
    });

    const savedItem = await this.planItemRepo.update(planItemId, {
      estimatedTime: estimatedMinutes,
    });
    if (!savedItem) throw new NotFoundException();

    await this.logPlanItemUpdate(
      savedItem,
      PlanLogActionType.ITEM_TIME_UPDATED,
      {
        oldEstimatedTime: item.estimatedTime,
        newEstimatedTime: estimatedMinutes,
      },
    );
    return session;
  }

  async updateItemStatus(
    teacherId: UserId,
    planId: string,
    planItemId: string,
    newStatus: PlanItemStatus,
    sessionId: string,
  ): Promise<UpdatePlanItemStatusResponse> {
    const planItem = await this.planItemRepo.findById(planItemId);
    if (!planItem) throw new NotFoundException();
    if (planItem.planId !== planId) {
      throw new BadRequestException('Plan item does not belong to plan.');
    }

    const plan = await this.verifyTeacherOwnsPlan(planId, teacherId);
    const planSession = this.findSessionInPlan(plan, sessionId);
    const item = this.findItemInSession(planSession, planItemId);

    const session = await this.sessionRepo.findById(sessionId);
    if (!session) throw new NotFoundException();

    if (newStatus === item.status) {
      throw new BadRequestException('Plan item already has this status.');
    }

    if (!this.canUpdatePlanItemStatus(item.status, newStatus)) {
      throw new BadRequestException('Invalid plan item status transition.');
    }

    const updatedItem: PlanItem = {
      ...item,
      status: newStatus,
    };

    this.replaceItemInSession(planSession, updatedItem);
    this.replaceItemInSession(session, updatedItem);
    planSession.usedDuration = this.calculateSessionUsedDuration(planSession);
    session.usedDuration = planSession.usedDuration;

    await this.plansRepo.update(plan.planId, { sessions: plan.sessions });
    await this.sessionRepo.update(sessionId, {
      items: session.items,
      usedDuration: session.usedDuration,
    });

    const savedItem = await this.planItemRepo.update(planItemId, {
      status: newStatus,
    });
    if (!savedItem) throw new NotFoundException();

    await this.logPlanItemUpdate(
      savedItem,
      this.getPlanLogActionForStatus(newStatus),
      {
        oldStatus: item.status,
        newStatus,
        targetSessionId: session.sessionId,
        targetSessionDate: session.sessionDate,
      },
    );
    return {
      item: savedItem,
      session,
      progress: this.calculatePlanProgress(plan),
    };
  }

  async getPlanProgress(
    teacherId: UserId,
    planId: string,
  ): Promise<PlanProgressSummary> {
    const plan = await this.verifyTeacherOwnsPlan(planId, teacherId);
    return this.calculatePlanProgress(plan);
  }

  async getPlanHistory(teacherId: UserId, planId: string): Promise<PlanLog[]> {
    await this.verifyTeacherOwnsPlan(planId, teacherId);
    const logs = await this.planLogsRepo.findByPlanId(planId);

    return logs.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
  }

  async getTeacherPlans(teacherId: UserId): Promise<Plan[]> {
    const plans = await this.plansRepo.findAll();

    return plans
      .filter((plan) => String(plan.teacherId) === String(teacherId))
      .sort(
        (a, b) =>
          this.getPlanCreatedTimestamp(b) - this.getPlanCreatedTimestamp(a),
      );
  }

  async getLatestTeacherPlan(teacherId: UserId): Promise<Plan | null> {
    const plans = await this.getTeacherPlans(teacherId);
    return plans[0] ?? null;
  }

  async getTeacherTodoList(
    teacherId: UserId,
    date: Date = new Date(),
  ): Promise<TeacherTodoItem[]> {
    const plans = await this.plansRepo.findAll();
    const todoItems = plans
      .filter((plan) => String(plan.teacherId) === String(teacherId))
      .flatMap((plan) =>
        plan.sessions
          .filter((session) => this.isSameDate(session.sessionDate, date))
          .flatMap((session) =>
            session.items
              .filter((item) => item.status === PlanItemStatus.PLANNED)
              .map((item) => ({
                planId: plan.planId,
                planName: plan.planName,
                subjectId: plan.subjectId,
                sessionId: session.sessionId,
                sessionDate: session.sessionDate,
                sessionWeekNo: session.sessionWeekNo,
                day: session.day,
                slotNumber: session.slotNumber,
                item,
              })),
          ),
      );

    return todoItems.sort(
      (a, b) =>
        this.getDateTime(a.sessionDate) - this.getDateTime(b.sessionDate) ||
        a.slotNumber - b.slotNumber,
    );
  }

  async replanFromSession(
    teacherId: UserId,
    planId: string,
    fromSessionId: string,
  ): Promise<ReplanPlanResponse> {
    if (!fromSessionId) {
      throw new BadRequestException('fromSessionId is required.');
    }

    const plan = await this.verifyTeacherOwnsPlan(planId, teacherId);
    const anchorIndex = plan.sessions.findIndex(
      (session) => session.sessionId === fromSessionId,
    );

    if (anchorIndex === -1) {
      throw new NotFoundException('Session not found');
    }

    const frozenSessions = plan.sessions.slice(0, anchorIndex);
    const futureSessions = plan.sessions.slice(anchorIndex);
    const itemsToReplan = this.sortItemsForReplanning(
      this.collectReplannableItems(futureSessions, anchorIndex),
    );
    const {
      sessions: replannedSessions,
      pace,
      unplacedItems,
    } = this.repackFutureSessions(futureSessions, itemsToReplan, anchorIndex);

    const updatedPlan: Plan = {
      ...plan,
      sessions: [...frozenSessions, ...replannedSessions],
    };

    await this.plansRepo.update(plan.planId, {
      sessions: updatedPlan.sessions,
    });
    await this.saveReplannedSessions(replannedSessions);
    await this.logPlanReplanned(
      updatedPlan,
      fromSessionId,
      pace,
      unplacedItems,
    );

    return {
      plan: updatedPlan,
      pace,
      planOverCapacity: unplacedItems.length > 0,
      unplacedItems,
    };
  }

  private collectReplannableItems(
    sessions: Session[],
    anchorIndex: number,
  ): PlanItem[] {
    return sessions.flatMap((session, index) =>
      session.items
        .filter((item) => item.status === PlanItemStatus.PLANNED)
        .map((item) => ({
          ...item,
          originalSessionOrder:
            item.originalSessionOrder ?? anchorIndex + index,
        })),
    );
  }

  private sortItemsForReplanning(items: PlanItem[]): PlanItem[] {
    return [...items].sort((a, b) => {
      const originalSessionDiff =
        (a.originalSessionOrder ?? 0) - (b.originalSessionOrder ?? 0);
      if (originalSessionDiff !== 0) return originalSessionDiff;

      if (a.unitNo !== b.unitNo) return a.unitNo - b.unitNo;
      if (a.lessonNo !== b.lessonNo) return a.lessonNo - b.lessonNo;
      return a.orderInLesson - b.orderInLesson;
    });
  }

  private repackFutureSessions(
    sessions: Session[],
    items: PlanItem[],
    anchorIndex: number,
  ): {
    sessions: Session[];
    pace: ReplanPaceSummary;
    unplacedItems: PlanItem[];
  } {
    const carriedForwardItemsByDay: Record<string, number> = {};
    let itemIndex = 0;

    const replannedSessions = sessions.map((session, sessionIndex) => {
      const fixedItems = session.items.filter(
        (item) => item.status !== PlanItemStatus.PLANNED,
      );
      const nextSession: Session = {
        ...session,
        items: [...fixedItems],
      };
      let usedDuration = this.calculateSessionUsedDuration(nextSession);
      const normalAvailableMinutes =
        nextSession.maxDuration - nextSession.reviewBufferMinutes;
      const maxAvailableMinutes =
        normalAvailableMinutes + nextSession.reviewBufferMinutes;

      while (itemIndex < items.length) {
        const item = items[itemIndex];
        const itemMinutes = Number(item.estimatedTime ?? 0);
        const fitsInSession = usedDuration + itemMinutes <= maxAvailableMinutes;

        if (!fitsInSession) {
          break;
        }

        const updatedItem = this.applyCarryForwardMetadata(
          item,
          session,
          anchorIndex + sessionIndex,
          carriedForwardItemsByDay,
        );

        nextSession.items.push(updatedItem);
        usedDuration += itemMinutes;
        itemIndex++;
      }

      nextSession.usedDuration = this.calculateSessionUsedDuration(nextSession);
      return nextSession;
    });

    const unplacedItems = items.slice(itemIndex);

    return {
      sessions: replannedSessions,
      pace: {
        carriedForwardItemsByDay,
        behindPace: Object.values(carriedForwardItemsByDay).some(
          (count) => count > 1,
        ),
      },
      unplacedItems,
    };
  }

  private applyCarryForwardMetadata(
    item: PlanItem,
    targetSession: Session,
    targetSessionIndex: number,
    carriedForwardItemsByDay: Record<string, number>,
  ): PlanItem {
    const originalSessionOrder =
      item.originalSessionOrder ?? targetSessionIndex;
    const wasCarriedForward = originalSessionOrder < targetSessionIndex;

    if (!wasCarriedForward) {
      return {
        ...item,
        sessionId: targetSession.sessionId,
        originalSessionOrder,
      };
    }

    const dayKey = this.toDateKey(targetSession.sessionDate);
    carriedForwardItemsByDay[dayKey] =
      (carriedForwardItemsByDay[dayKey] ?? 0) + 1;

    return {
      ...item,
      sessionId: targetSession.sessionId,
      originalSessionId: item.originalSessionId ?? item.sessionId,
      originalSessionOrder,
      carriedForwardCount: (item.carriedForwardCount ?? 0) + 1,
    };
  }

  private async saveReplannedSessions(sessions: Session[]): Promise<void> {
    for (const session of sessions) {
      await this.sessionRepo.update(session.sessionId, {
        items: session.items,
        usedDuration: session.usedDuration,
      });

      for (const item of session.items) {
        await this.planItemRepo.update(item.planItemId, item);
      }
    }
  }

  private toDateKey(date: Date): string {
    return new Date(date).toISOString().slice(0, 10);
  }

  private canUpdatePlanItemStatus(
    currentStatus: PlanItemStatus,
    newStatus: PlanItemStatus,
  ): boolean {
    const allowedTransitions: Record<PlanItemStatus, PlanItemStatus[]> = {
      [PlanItemStatus.PLANNED]: [
        PlanItemStatus.COMPLETED,
        PlanItemStatus.POSTPONED,
        PlanItemStatus.CANCELLED,
      ],
      [PlanItemStatus.POSTPONED]: [PlanItemStatus.PLANNED],
      [PlanItemStatus.COMPLETED]: [],
      [PlanItemStatus.CANCELLED]: [],
    };

    return allowedTransitions[currentStatus].includes(newStatus);
  }

  private async verifyTeacherOwnsPlan(
    planId: string,
    teacherId: UserId,
  ): Promise<Plan> {
    const plan = await this.plansRepo.findById(planId);
    if (!plan) throw new NotFoundException();

    if (String(plan.teacherId) !== String(teacherId)) {
      throw new ForbiddenException('Teacher does not own this plan.');
    }

    return plan;
  }

  private async logPlanItemUpdate(
    item: PlanItem,
    actionType: PlanLogActionType,
    metadata: Record<string, unknown> = {},
  ): Promise<void> {
    await this.planLogsRepo.create({
      planLogId: `plan_log_${randomUUID()}`,
      planId: item.planId,
      sessionId: item.sessionId,
      planItemId: item.planItemId,
      curriculumItemId: item.curriculumItemId,
      actionType,
      description: this.buildPlanItemLogDescription(actionType, item, metadata),
      createdAt: new Date(),
      metadata: {
        ...metadata,
        status: item.status,
        estimatedTime: item.estimatedTime,
      },
    });
  }

  private async logPlanGenerated(plan: Plan): Promise<void> {
    await this.planLogsRepo.create({
      planLogId: `plan_log_${randomUUID()}`,
      planId: plan.planId,
      actionType: PlanLogActionType.PLAN_GENERATED,
      description: `Generated ${plan.planName}.`,
      createdAt: new Date(),
      metadata: {
        planName: plan.planName,
        subjectId: plan.subjectId,
        totalWeeks: plan.totalWeeks,
        sessionCount: plan.sessions.length,
        itemCount: plan.sessions.reduce(
          (total, session) => total + session.items.length,
          0,
        ),
      },
    });
  }

  private async logPlanReplanned(
    plan: Plan,
    fromSessionId: string,
    pace: ReplanPaceSummary,
    unplacedItems: PlanItem[],
  ): Promise<void> {
    const movedItemsCount = Object.values(pace.carriedForwardItemsByDay).reduce(
      (total, count) => total + count,
      0,
    );

    await this.planLogsRepo.create({
      planLogId: `plan_log_${randomUUID()}`,
      planId: plan.planId,
      sessionId: fromSessionId,
      actionType: PlanLogActionType.PLAN_REGENERATED,
      description: `Replanned ${plan.planName} from session ${fromSessionId}. Moved ${movedItemsCount} item(s).`,
      createdAt: new Date(),
      metadata: {
        fromSessionId,
        movedItemsCount,
        behindPace: pace.behindPace,
        carriedForwardItemsByDay: pace.carriedForwardItemsByDay,
        planOverCapacity: unplacedItems.length > 0,
        unplacedItemIds: unplacedItems.map((item) => item.planItemId),
      },
    });
  }

  private getPlanLogActionForStatus(status: PlanItemStatus): PlanLogActionType {
    switch (status) {
      case PlanItemStatus.COMPLETED:
        return PlanLogActionType.ITEM_COMPLETED;
      case PlanItemStatus.POSTPONED:
        return PlanLogActionType.ITEM_POSTPONED;
      case PlanItemStatus.CANCELLED:
        return PlanLogActionType.ITEM_CANCELLED;
      default:
        return PlanLogActionType.ITEM_REINSERTED;
    }
  }

  private buildPlanItemLogDescription(
    actionType: PlanLogActionType,
    item: PlanItem,
    metadata: Record<string, unknown>,
  ): string {
    switch (actionType) {
      case PlanLogActionType.ITEM_TIME_UPDATED:
        return `Updated "${item.title}" duration from ${metadata.oldEstimatedTime} min to ${metadata.newEstimatedTime} min.`;
      case PlanLogActionType.ITEM_COMPLETED:
        return `Marked "${item.title}" as completed.`;
      case PlanLogActionType.ITEM_POSTPONED:
        return `Postponed "${item.title}".`;
      case PlanLogActionType.ITEM_CANCELLED:
        return `Cancelled "${item.title}".`;
      case PlanLogActionType.ITEM_REINSERTED:
        return `Reinserted "${item.title}" into the plan.`;
      default:
        return `Updated "${item.title}".`;
    }
  }

  private findSessionInPlan(plan: Plan, sessionId: string): Session {
    const session = plan.sessions.find(
      (session) => session.sessionId === sessionId,
    );
    if (!session) throw new NotFoundException();

    return session;
  }

  private findItemInSession(session: Session, planItemId: string): PlanItem {
    const item = session.items.find((item) => item.planItemId === planItemId);
    if (!item) throw new NotFoundException();

    return item;
  }

  private replaceItemInSession(session: Session, updatedItem: PlanItem): void {
    session.items = session.items.map((item) =>
      item.planItemId === updatedItem.planItemId ? updatedItem : item,
    );
  }

  private calculateSessionUsedDuration(session: Session): number {
    return session.items
      .filter(
        (item) =>
          item.status !== PlanItemStatus.CANCELLED &&
          item.status !== PlanItemStatus.POSTPONED,
      )
      .reduce((total, item) => total + Number(item.estimatedTime ?? 0), 0);
  }

  private calculatePlanProgress(plan: Plan): PlanProgressSummary {
    const items = plan.sessions.flatMap((session) => session.items);
    const cancelledItems = items.filter(
      (item) => item.status === PlanItemStatus.CANCELLED,
    ).length;
    const activeItems = items.filter(
      (item) => item.status !== PlanItemStatus.CANCELLED,
    );
    const completedItems = activeItems.filter(
      (item) => item.status === PlanItemStatus.COMPLETED,
    ).length;
    const totalItems = activeItems.length;
    const remainingItems = totalItems - completedItems;
    const progressPercentage =
      totalItems === 0 ? 0 : Math.round((completedItems / totalItems) * 100);

    return {
      planId: plan.planId,
      totalItems,
      completedItems,
      remainingItems,
      cancelledItems,
      progressPercentage,
    };
  }

  private isSameDate(left: Date, right: Date): boolean {
    const leftDate = new Date(left);
    const rightDate = new Date(right);

    return (
      leftDate.getFullYear() === rightDate.getFullYear() &&
      leftDate.getMonth() === rightDate.getMonth() &&
      leftDate.getDate() === rightDate.getDate()
    );
  }

  private getDateTime(date: Date): number {
    return new Date(date).getTime();
  }

  private sortCurriculumItems(
    curriculumItems: CurriculumItem[],
  ): CurriculumItem[] {
    return [...curriculumItems].sort((a, b) => {
      if (a.unitNo !== b.unitNo) {
        return a.unitNo - b.unitNo;
      }

      if (a.lessonNo !== b.lessonNo) {
        return a.lessonNo - b.lessonNo;
      }

      return a.orderInLesson - b.orderInLesson;
    });
  }

  private async calculateSkillWeight(
    curriculumItem: CurriculumItem,
  ): Promise<number> {
    const priorityRows = await this.statService.sortWeakestSkills();

    const matchedSkill = priorityRows.find(
      (row) => curriculumItem.skillsSupported.includes(row.skillId), //need this to be fixed
    );

    const priorityPoints = matchedSkill
      ? priorityToPoints[matchedSkill.priority]
      : 0;

    const difficultyToPoints: Record<number, number> = {
      1: 3,
      2: 6,
      3: 10,
    };

    const difficultyPoints =
      difficultyToPoints[curriculumItem.difficulity] ?? 0;

    return priorityPoints + difficultyPoints;
  }

  private weightToMinutes(weight: number): number {
    if (weight >= 18) return 15;
    if (weight >= 14) return 12;
    if (weight >= 10) return 9;
    return 6;
  }

  private async calculateEstimatedTime(
    curriculumItem: CurriculumItem,
  ): Promise<CurriculumItem> {
    const weight = await this.calculateSkillWeight(curriculumItem);
    const minutes = this.weightToMinutes(weight);

    return {
      ...curriculumItem,
      estimatedTime: minutes,
    };
  }

  private async findSubjectOffering(
    teacherId: UserId,
    subjectId: SubjectId,
  ): Promise<SubjectOffering> {
    const offerings = await this.subjectOfferingsRepo.findAll();
    const subjectOffering = offerings.find(
      (offering) =>
        String(offering.teacherId) === String(teacherId) &&
        String(offering.subjectId) === String(subjectId),
    );

    if (!subjectOffering) {
      throw new NotFoundException(
        'No subject offering found for this teacher and subject.',
      );
    }

    return subjectOffering;
  }

  private sortWeeklySlots(slots: WeeklySlotDTO[]): WeeklySlotDTO[] {
    return [...slots].sort((a, b) => {
      const dayDiff = DAY_ORDER.indexOf(a.day) - DAY_ORDER.indexOf(b.day);
      if (dayDiff !== 0) {
        return dayDiff;
      }

      return a.slotNumber - b.slotNumber;
    });
  }

  private buildSessionsFromSlots(
    teacherId: UserId,
    subjectId: SubjectId,
    weeklySlots: WeeklySlotDTO[],
    timedItems: CurriculumItem[],
    totalWeeks: number,
    planId: string,
  ): Session[] {
    if (weeklySlots.length === 0 || timedItems.length === 0) {
      return [];
    }

    const sessions: Session[] = [];
    let itemIndex = 0;

    for (let weekIndex = 0; weekIndex < totalWeeks; weekIndex++) {
      for (const slot of weeklySlots) {
        if (itemIndex >= timedItems.length) {
          return sessions;
        }

        const sessionId = `session_${teacherId}_${subjectId}_${weekIndex + 1}_${slot.day}_${slot.slotNumber}`;
        const sessionNumber = sessions.length + 1;
        const reviewBufferMinutes =
          sessionNumber % REVIEW_BUFFER_INTERVAL === 0
            ? REVIEW_BUFFER_MINUTES
            : 0;
        const availableMinutes =
          DEFAULT_SESSION_DURATION_MINUTES - reviewBufferMinutes;
        const itemsForSession: PlanItem[] = [];
        let usedDuration = 0;

        while (itemIndex < timedItems.length) {
          const currentItem = timedItems[itemIndex];
          const planItem: PlanItem = {
            ...currentItem,
            planId,
            sessionId,
            planItemId: `plan_item_${randomUUID()}`,
            title: currentItem.name,
            status: PlanItemStatus.PLANNED,
          };
          const itemMinutes = Number(planItem.estimatedTime ?? 0);

          if (
            itemsForSession.length > 0 &&
            usedDuration + itemMinutes > availableMinutes
          ) {
            break;
          }

          if (itemsForSession.length === 0 && itemMinutes > availableMinutes) {
            itemsForSession.push(planItem);
            usedDuration += itemMinutes;
            itemIndex++;
            break;
          }

          itemsForSession.push(planItem);
          usedDuration += itemMinutes;
          itemIndex++;
        }

        sessions.push({
          sessionId,
          teacherId: String(teacherId),
          subjectId: String(subjectId),
          day: slot.day,
          items: itemsForSession,
          maxDuration: DEFAULT_SESSION_DURATION_MINUTES,
          usedDuration,
          reviewBufferMinutes,
          slotNumber: slot.slotNumber,
          sessionDate: this.buildSessionDate(slot.day, weekIndex),
          sessionWeekNo: weekIndex + 1,
        });
      }
    }

    return sessions;
  }

  private buildSessionDate(day: WeekDay, weekIndex: number): Date {
    const now = new Date();
    const startOfWeek = new Date(now);
    startOfWeek.setHours(0, 0, 0, 0);
    startOfWeek.setDate(now.getDate() - now.getDay());

    const dayOffset = DAY_ORDER.indexOf(day);
    const sessionDate = new Date(startOfWeek);
    sessionDate.setDate(startOfWeek.getDate() + weekIndex * 7 + dayOffset);
    return sessionDate;
  }

  private getPlanCreatedTimestamp(plan: Plan): number {
    const planIdParts = String(plan.planId).split('_');
    const rawTimestamp = Number(planIdParts[planIdParts.length - 1]);

    if (!Number.isNaN(rawTimestamp) && rawTimestamp > 0) {
      return rawTimestamp;
    }

    return new Date(plan.startDate).getTime();
  }
}
