import { Session } from './session';
import { PlanId, SubjectId, UserId } from './ids';

export class Plan {
  planId: PlanId;
  planName: string;
  subjectId: SubjectId;
  startDate: Date;
  totalWeeks: number;
  teacherId: UserId;
  sessions: Session[]; //these sessions contain the cur items
  autoGenerated: boolean;
  planJson: string; //to be changed later
}
