import { PlanId, SubjectId, UserId } from './ids';

export class Plan {
  planId: PlanId;
  planName: string;
  subjectId: SubjectId;
  startDate: Date;
  teacherId: UserId;
  autoGenerated: boolean;
  planJson: string; //to be changes later
}
