using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace GP.Models
{
    public class Plan : BaseEntity
    {
        [Key]
        public int PlanId { get; set; }
        public string PlanName { get; set; }
        public int SubjectId { get; set; }
        public Subject Subject { get; set; }
        public DateTime StartDate { get; set; }
        public int TotalWeeks { get; set; }
        public int TeacherId { get; set; }
        public  Teacher Teacher { get; set; }
        public List<Session> Sessions { get; set; }
        public bool AutoGenerated { get; set; }
        public string PlanJson { get; set; }
    }
}
